"""Integration tests for /admin/users routes.

Covers POST (create, regression coverage) and GET / PATCH /admin/users/<app_key>
(lookup + edit, regression coverage). Same in-memory sqlite + monkeypatched DB engine
pattern as test_account_me_endpoint.py.
"""

from __future__ import annotations

import logging
import sqlite3
from decimal import Decimal

import pytest
from sqlalchemy import create_engine, text


sqlite3.register_adapter(Decimal, str)


AUTH_TOKEN = "test-bff-token"

# Mirrors the post-20260526_0002 schema, with one divergence from
# test_account_me_endpoint.py: `id` is nullable here because production databases use
# `GENERATED BY DEFAULT AS IDENTITY` (auto-fills on INSERT) and sqlite
# has no equivalent default. The route under test intentionally omits
# `id` from its INSERT, so the NOT NULL would fail before any trigger
# could fill it. UNIQUE is retained.
SQLITE_SCHEMA = """
CREATE TABLE users (
    app_key TEXT PRIMARY KEY,
    id INTEGER UNIQUE,
    balance_points NUMERIC NOT NULL DEFAULT 1000 CHECK (balance_points >= 0),
    nickname TEXT,
    mobile TEXT,
    email TEXT,
    company_name TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


@pytest.fixture()
def sqlite_engine():
    engine = create_engine(
        "sqlite:///:memory:", connect_args={"check_same_thread": False}
    )
    with engine.begin() as conn:
        conn.execute(text(SQLITE_SCHEMA))
    yield engine
    engine.dispose()


@pytest.fixture()
def client(sqlite_engine, monkeypatch):
    import server

    monkeypatch.setenv("PRICING_BFF_AUTH_TOKEN", AUTH_TOKEN)
    monkeypatch.setattr(server, "get_db_engine", lambda: sqlite_engine)
    monkeypatch.setattr(
        server, "get_db_core_connection", lambda: sqlite_engine.connect()
    )
    return server.app.test_client()


def _auth_headers() -> dict[str, str]:
    return {"Authorization": f"Bearer {AUTH_TOKEN}"}


# ---------- happy path ----------


def test_default_balance_creates_user_with_grid_key(client, sqlite_engine):
    res = client.post("/admin/users", headers=_auth_headers(), json={})
    assert res.status_code == 201
    body = res.get_json()
    assert body["success"] is True
    app_key = body["data"]["app_key"]
    assert app_key.startswith("grid_")
    assert len(app_key) == len("grid_") + 22

    with sqlite_engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT balance_points, nickname, mobile, email, company_name "
                "FROM users WHERE app_key = :k"
            ),
            {"k": app_key},
        ).mappings().first()
    assert row is not None
    assert Decimal(str(row["balance_points"])) == Decimal("1000")
    assert row["nickname"] is None
    assert row["mobile"] is None
    assert row["email"] is None
    assert row["company_name"] is None


def test_full_profile_round_trips(client, sqlite_engine):
    res = client.post(
        "/admin/users",
        headers=_auth_headers(),
        json={
            "balance": "2500.50",
            "nickname": "Demo User",
            "mobile": "13912345678",
            "email": "user@example.com",
            "company_name": "Example Inc",
        },
    )
    assert res.status_code == 201
    app_key = res.get_json()["data"]["app_key"]

    with sqlite_engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT balance_points, nickname, mobile, email, company_name "
                "FROM users WHERE app_key = :k"
            ),
            {"k": app_key},
        ).mappings().first()
    assert Decimal(str(row["balance_points"])) == Decimal("2500.50")
    assert row["nickname"] == "Demo User"
    assert row["mobile"] == "13912345678"
    assert row["email"] == "user@example.com"
    assert row["company_name"] == "Example Inc"


def test_blank_profile_strings_become_null(client, sqlite_engine):
    res = client.post(
        "/admin/users",
        headers=_auth_headers(),
        json={"nickname": "  ", "email": ""},
    )
    assert res.status_code == 201
    app_key = res.get_json()["data"]["app_key"]
    with sqlite_engine.connect() as conn:
        row = conn.execute(
            text("SELECT nickname, email FROM users WHERE app_key = :k"),
            {"k": app_key},
        ).mappings().first()
    assert row["nickname"] is None
    assert row["email"] is None


# ---------- validation ----------


def test_non_object_body_returns_400(client):
    res = client.post(
        "/admin/users", headers=_auth_headers(), json=["not", "an", "object"]
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_non_numeric_balance_returns_400(client):
    res = client.post(
        "/admin/users", headers=_auth_headers(), json={"balance": "abc"}
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_negative_balance_returns_400(client):
    res = client.post(
        "/admin/users", headers=_auth_headers(), json={"balance": "-1"}
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_non_string_profile_field_returns_400(client):
    res = client.post(
        "/admin/users", headers=_auth_headers(), json={"nickname": 123}
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


# ---------- auth ----------


def test_missing_bearer_returns_401(client):
    res = client.post("/admin/users", json={})
    assert res.status_code == 401
    assert res.get_json()["error"]["code"] == "UNAUTHORIZED"


def test_wrong_bearer_returns_401(client):
    res = client.post(
        "/admin/users",
        headers={"Authorization": "Bearer wrong-token"},
        json={},
    )
    assert res.status_code == 401
    assert res.get_json()["error"]["code"] == "UNAUTHORIZED"


def test_missing_bff_token_env_returns_503(sqlite_engine, monkeypatch):
    """If operators forgot to set PRICING_BFF_AUTH_TOKEN, the route fails closed
    (rather than letting an unauthenticated caller through)."""
    import server

    monkeypatch.delenv("PRICING_BFF_AUTH_TOKEN", raising=False)
    monkeypatch.setattr(server, "get_db_engine", lambda: sqlite_engine)
    res = server.app.test_client().post("/admin/users", json={})
    assert res.status_code == 503
    assert res.get_json()["error"]["code"] == "PRICING_BFF_NOT_CONFIGURED"


# ---------- GET /admin/users/<app_key> ----------


def _create_user(client, **profile):
    res = client.post("/admin/users", headers=_auth_headers(), json=profile)
    assert res.status_code == 201
    return res.get_json()["data"]["app_key"]


def test_get_returns_user(client):
    app_key = _create_user(
        client,
        balance="2500.50",
        nickname="Demo User",
        mobile="13912345678",
        email="user@example.com",
        company_name="Example Inc",
    )
    res = client.get(f"/admin/users/{app_key}", headers=_auth_headers())
    assert res.status_code == 200
    data = res.get_json()["data"]
    assert data["app_key"] == app_key
    assert Decimal(data["balance"]) == Decimal("2500.50")
    assert data["nickname"] == "Demo User"
    assert data["mobile"] == "13912345678"
    assert data["email"] == "user@example.com"
    assert data["company_name"] == "Example Inc"
    assert data["created_at"]


def test_get_unknown_app_key_returns_404(client):
    # Valid format (grid_ + 22 base62 chars) but does not exist.
    res = client.get(
        "/admin/users/grid_AAAAAAAAAAAAAAAAAAAAAA", headers=_auth_headers()
    )
    assert res.status_code == 404
    assert res.get_json()["error"]["code"] == "USER_NOT_FOUND"


def test_get_malformed_app_key_returns_400(client):
    res = client.get(
        "/admin/users/not-a-grid-key", headers=_auth_headers()
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_get_missing_bearer_returns_401(client):
    app_key = _create_user(client)
    res = client.get(f"/admin/users/{app_key}")
    assert res.status_code == 401


# ---------- PATCH /admin/users/<app_key> ----------


def test_patch_updates_balance_and_profile(client, sqlite_engine):
    app_key = _create_user(client, nickname="Old")
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"balance": "5000", "nickname": "New"},
    )
    assert res.status_code == 200
    data = res.get_json()["data"]
    assert Decimal(data["balance"]) == Decimal("5000")
    assert data["nickname"] == "New"

    with sqlite_engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT balance_points, nickname FROM users WHERE app_key = :k"
            ),
            {"k": app_key},
        ).mappings().first()
    assert Decimal(str(row["balance_points"])) == Decimal("5000")
    assert row["nickname"] == "New"


def test_patch_omitted_fields_remain_unchanged(client, sqlite_engine):
    app_key = _create_user(
        client,
        balance="1500",
        nickname="Demo User",
        email="user@example.com",
        company_name="Example Inc",
    )
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"nickname": "Demo User 2"},
    )
    assert res.status_code == 200
    with sqlite_engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT balance_points, nickname, email, company_name "
                "FROM users WHERE app_key = :k"
            ),
            {"k": app_key},
        ).mappings().first()
    assert Decimal(str(row["balance_points"])) == Decimal("1500")
    assert row["nickname"] == "Demo User 2"
    assert row["email"] == "user@example.com"
    assert row["company_name"] == "Example Inc"


def test_patch_null_profile_field_clears_it(client, sqlite_engine):
    app_key = _create_user(client, nickname="Demo User", email="user@example.com")
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"nickname": None},
    )
    assert res.status_code == 200
    with sqlite_engine.connect() as conn:
        row = conn.execute(
            text("SELECT nickname, email FROM users WHERE app_key = :k"),
            {"k": app_key},
        ).mappings().first()
    assert row["nickname"] is None
    # Sibling profile field stays put.
    assert row["email"] == "user@example.com"


def test_patch_blank_string_profile_becomes_null(client, sqlite_engine):
    app_key = _create_user(client, nickname="Demo User")
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"nickname": "   "},
    )
    assert res.status_code == 200
    with sqlite_engine.connect() as conn:
        row = conn.execute(
            text("SELECT nickname FROM users WHERE app_key = :k"),
            {"k": app_key},
        ).mappings().first()
    assert row["nickname"] is None


def test_patch_empty_body_is_noop(client, sqlite_engine):
    app_key = _create_user(client, balance="1500", nickname="Demo User")
    res = client.patch(
        f"/admin/users/{app_key}", headers=_auth_headers(), json={}
    )
    assert res.status_code == 200
    data = res.get_json()["data"]
    assert Decimal(data["balance"]) == Decimal("1500")
    assert data["nickname"] == "Demo User"


def test_patch_null_balance_returns_400(client):
    app_key = _create_user(client)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"balance": None},
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_negative_balance_returns_400(client):
    app_key = _create_user(client)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"balance": "-1"},
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_non_numeric_balance_returns_400(client):
    app_key = _create_user(client)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"balance": "abc"},
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_non_object_body_returns_400(client):
    app_key = _create_user(client)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json=["not", "an", "object"],
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_non_string_profile_field_returns_400(client):
    app_key = _create_user(client)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"nickname": 123},
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_unknown_app_key_returns_404(client):
    res = client.patch(
        "/admin/users/grid_AAAAAAAAAAAAAAAAAAAAAA",
        headers=_auth_headers(),
        json={"nickname": "Demo User"},
    )
    assert res.status_code == 404
    assert res.get_json()["error"]["code"] == "USER_NOT_FOUND"


def test_patch_malformed_app_key_returns_400(client):
    res = client.patch(
        "/admin/users/not-a-grid-key",
        headers=_auth_headers(),
        json={"nickname": "Demo User"},
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_missing_bearer_returns_401(client):
    app_key = _create_user(client)
    res = client.patch(f"/admin/users/{app_key}", json={"nickname": "Demo User"})
    assert res.status_code == 401


# ---------- audit logging ----------


def _audit_record(caplog, event: str):
    """Return the most recent LogRecord whose `event` extra matches.

    `caplog.records` carries the original LogRecord objects (not the
    formatted strings), so we can introspect the `extra=` kwargs the
    route passed in."""
    for rec in reversed(caplog.records):
        if getattr(rec, "event", None) == event:
            return rec
    raise AssertionError(
        f"no log record with event={event!r}; saw events: "
        f"{[getattr(r, 'event', None) for r in caplog.records]}"
    )


def test_create_emits_audit_log_with_actor_ip(client, caplog):
    caplog.set_level(logging.INFO, logger="server")
    headers = {**_auth_headers(), "X-Admin-Operator-IP": "203.0.113.7"}
    res = client.post(
        "/admin/users",
        headers=headers,
        json={
            "balance": "1500",
            "nickname": "Demo User",
            "email": "user@example.com",
            "mobile": "13912345678",
        },
    )
    assert res.status_code == 201
    app_key = res.get_json()["data"]["app_key"]

    rec = _audit_record(caplog, "admin.users.create")
    assert rec.actor_ip == "203.0.113.7"
    assert rec.app_key == app_key
    # Balance is recorded verbatim (financial signal, not PII).
    assert rec.balance == "1500"
    # Profile fields are recorded as names only — never raw values.
    assert set(rec.profile_fields_set) == {"nickname", "email", "mobile"}


def test_create_audit_log_does_not_contain_pii_values(client, caplog):
    """Regression coverage (security hardening): mobile / email / nickname /
    company_name values must NOT appear anywhere in the audit log."""
    caplog.set_level(logging.INFO, logger="server")
    res = client.post(
        "/admin/users",
        headers=_auth_headers(),
        json={
            "nickname": "DemoPersonalName",
            "mobile": "13912345678",
            "email": "user@private.example",
            "company_name": "AcmeCo",
        },
    )
    assert res.status_code == 201
    rec = _audit_record(caplog, "admin.users.create")
    rec_repr = repr(vars(rec))
    for pii in ("DemoPersonalName", "13912345678", "user@private.example", "AcmeCo"):
        assert pii not in rec_repr, f"audit log leaks PII: {pii!r}"


def test_create_without_operator_ip_records_unknown(client, caplog):
    caplog.set_level(logging.INFO, logger="server")
    res = client.post("/admin/users", headers=_auth_headers(), json={})
    assert res.status_code == 201
    rec = _audit_record(caplog, "admin.users.create")
    assert rec.actor_ip == "unknown"


def test_patch_emits_audit_log_with_diff_and_ip(client, caplog):
    app_key = _create_user(client, balance="1000", nickname="Old", email="a@example.com")
    caplog.clear()
    caplog.set_level(logging.INFO, logger="server")
    headers = {**_auth_headers(), "X-Admin-Operator-IP": "198.51.100.42"}
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=headers,
        json={"balance": "5000", "nickname": "New"},
    )
    assert res.status_code == 200

    rec = _audit_record(caplog, "admin.users.update")
    assert rec.actor_ip == "198.51.100.42"
    assert rec.app_key == app_key
    # Balance diff carries verbatim values (financial signal).
    assert rec.balance_before in {"1000", "1000.00"}
    assert rec.balance_after == "5000"
    # Profile change is recorded as a name list, not raw values.
    assert rec.profile_changed == ["nickname"]


def test_patch_audit_log_does_not_contain_pii_values(client, caplog):
    """Regression coverage (security hardening): mobile / email / nickname /
    company_name values must NOT appear in update audit logs either,
    in before OR after position."""
    app_key = _create_user(
        client,
        nickname="OldName",
        email="old@private.example",
        mobile="13900000000",
        company_name="OldCo",
    )
    caplog.clear()
    caplog.set_level(logging.INFO, logger="server")
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={
            "nickname": "NewName",
            "email": "new@private.example",
            "mobile": "13911111111",
            "company_name": "NewCo",
        },
    )
    assert res.status_code == 200
    rec = _audit_record(caplog, "admin.users.update")
    rec_repr = repr(vars(rec))
    pii_values = (
        "OldName", "NewName",
        "old@private.example", "new@private.example",
        "13900000000", "13911111111",
        "OldCo", "NewCo",
    )
    for pii in pii_values:
        assert pii not in rec_repr, f"audit log leaks PII: {pii!r}"


def test_patch_noop_when_value_unchanged_omits_field_from_diff(client, caplog):
    app_key = _create_user(client, balance="1000", nickname="Demo User")
    caplog.clear()
    caplog.set_level(logging.INFO, logger="server")
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"nickname": "Demo User"},  # same as before
    )
    assert res.status_code == 200
    rec = _audit_record(caplog, "admin.users.update")
    # nickname was passed but did not change → empty diff signals.
    assert rec.balance_before is None
    assert rec.balance_after is None
    assert rec.profile_changed == []


# ---------- non-finite balance (security hardening) ----------


def test_create_nan_balance_returns_400(client):
    res = client.post(
        "/admin/users", headers=_auth_headers(), json={"balance": "NaN"}
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_create_infinity_balance_returns_400(client):
    res = client.post(
        "/admin/users", headers=_auth_headers(), json={"balance": "Infinity"}
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_nan_balance_returns_400(client):
    app_key = _create_user(client)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"balance": "NaN"},
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


def test_patch_infinity_balance_returns_400(client):
    app_key = _create_user(client)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"balance": "Infinity"},
    )
    assert res.status_code == 400
    assert res.get_json()["error"]["code"] == "BAD_REQUEST"


# ---------- refresh-after-update race (security hardening) ----------


def test_patch_refresh_race_returns_404(client, sqlite_engine, monkeypatch):
    """If the row vanishes between the UPDATE commit and the refresh
    SELECT, the route must return a clean 404 envelope, not a 500 from
    serializing `None`."""
    app_key = _create_user(client, balance="1000", nickname="Demo User")

    import server

    # First call returns the row (before-lookup); subsequent calls
    # return None to simulate the row being deleted concurrently.
    real_get = server.admin_get_user_by_app_key
    calls = {"n": 0}

    def flaky_get(engine, key):
        calls["n"] += 1
        if calls["n"] == 1:
            return real_get(engine, key)
        return None

    monkeypatch.setattr(server, "admin_get_user_by_app_key", flaky_get)
    res = client.patch(
        f"/admin/users/{app_key}",
        headers=_auth_headers(),
        json={"nickname": "New"},
    )
    assert res.status_code == 404
    assert res.get_json()["error"]["code"] == "USER_NOT_FOUND"
