"""extend users table with id + profile fields (nickname/mobile/email/company_name)

Revision ID: 20260526_0002
Revises: 20260526_0001
Create Date: 2026-05-26

Adds end-user profile fields to support the `/account/me` endpoint ,
the first reseller-mediated replacement for the legacy direct-to-upstream
`/api/account/balance` BFF route on narrator-ai-web.

Schema changes:
- `id`: new INTEGER IDENTITY column. Existing rows are backfilled with
  `ROW_NUMBER() OVER (ORDER BY created_at)`. The IDENTITY sequence is
  then bumped to `MAX(id) + 1` so future inserts continue safely. `id`
  is UNIQUE NOT NULL but NOT the primary key — `app_key` stays as PK to
  keep the existing auth lookup (`WHERE app_key = :key`) untouched and to avoid
  a PK swap on an already-deployed table.
- `nickname`, `mobile`, `email`, `company_name`: all `TEXT NULL`. The
  API masks `mobile` at the boundary (first 3 + last 3 + `*` for the
  middle 4); the DB stores the raw value.

Downgrade drops the 5 added columns and the identity sequence; the
table itself + the seeded rows survive.
"""

from __future__ import annotations

from alembic import op


revision = "20260526_0002"
down_revision = "20260526_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1) Add id as nullable first so we can backfill, then promote to NOT NULL
    #    UNIQUE. (PostgreSQL won't let you add a NOT NULL column without a
    #    DEFAULT when the table has rows — IDENTITY default would still be
    #    applied row-by-row but explicit two-step is clearer.)
    op.execute("ALTER TABLE users ADD COLUMN id INTEGER")
    op.execute(
        """
        WITH ordered AS (
            SELECT app_key, ROW_NUMBER() OVER (ORDER BY created_at, app_key) AS rn
            FROM users
        )
        UPDATE users
           SET id = ordered.rn
          FROM ordered
         WHERE users.app_key = ordered.app_key
        """
    )
    op.execute("ALTER TABLE users ALTER COLUMN id SET NOT NULL")
    op.execute("ALTER TABLE users ADD CONSTRAINT users_id_unique UNIQUE (id)")

    # 2) Promote `id` to a true GENERATED BY DEFAULT AS IDENTITY column so
    #    information_schema.columns.is_identity reads 'YES' and pg_dump /
    #    schema-validation tools recognize it correctly (review
    #    caution on regression coverage). Naming the sequence explicitly lets the setval
    #    below find it; ADD GENERATED creates the sequence at MINVALUE 1.
    op.execute(
        "ALTER TABLE users ALTER COLUMN id "
        "ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME users_id_seq)"
    )
    # 3) Advance the identity sequence past MAX(id) so future inserts
    #    don't collide with the backfilled rows.
    #    Empty-table safety (review security-sensitive on regression coverage):
    #    setval cannot accept 0 — PG sequences default to MINVALUE 1, so
    #    `setval(seq, 0, true)` raises "value 0 is out of bounds". Pass
    #    `is_called=EXISTS(...)` instead: false on empty (next nextval=1),
    #    true on non-empty (next nextval=MAX(id)+1).
    op.execute(
        "SELECT setval("
        "  'users_id_seq', "
        "  COALESCE((SELECT MAX(id) FROM users), 1), "
        "  EXISTS (SELECT 1 FROM users)"
        ")"
    )

    # 3) Profile fields. All nullable on purpose — older keys (and keys
    #    issued without --nickname etc) may legitimately have no profile.
    op.execute("ALTER TABLE users ADD COLUMN nickname TEXT")
    op.execute("ALTER TABLE users ADD COLUMN mobile TEXT")
    op.execute("ALTER TABLE users ADD COLUMN email TEXT")
    op.execute("ALTER TABLE users ADD COLUMN company_name TEXT")


def downgrade() -> None:
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS company_name")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS email")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS mobile")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS nickname")
    # DROP IDENTITY removes both the GENERATED clause AND the owned sequence
    # in one step — no separate DROP SEQUENCE needed.
    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_id_unique")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS id")
